services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - meeting-room

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - meeting-room
  
  reverse-proxy:
    container_name: reverse-proxy
    build: ./nginx
    depends_on:
      - frontend
    ports:
      - "443:443"
    networks:
      - meeting-room
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  meeting-room:
    driver: bridge
